$(document).ready(function(){

  $('.titleHide').hide();
  $('.optional').hide();
  $('.mediaContent').hide();
  $('.catArea').hide();

//TIRES MENU BEGIN
  $('#stiToggle').click(function(event){
    $('.optional').hide();
    $('.sti245_1').show();
    $('.sti245_2').show();
  });
  $('.sti245_1').click(function(event){
    $('.titleHide').hide();
    $('.sti245_1Title').show();
  });
  $('.sti245_2').click(function(event){
    $('.titleHide').hide();
    $('.sti245_2Title').show();
  });
  $('#wrxToggle').click(function(event){
    $('.optional').hide();
    $('.wrx235').show();
    $('.wrx245').show();
  });
  $('.wrx235').click(function(event){
    $('.titleHide').hide();
    $('.wrx235Title').show();
  });
  $('.wrx245').click(function(event){
    $('.titleHide').hide();
    $('.wrx245Title').show();
  });

//TIRES MENU END
//---------------------------------------
//ACCESSORIES MENU BEGIN
  $('#sportExhaust').click(function(event){
    $('.optional').hide();
    $('.titleHide').hide();
    $('.sportExhaustTitle').show();
  });
  $('#radarDetector').click(function(event){
    $('.optional').hide();
    $('#k40').show();
    $('#escort').show();
  });
  $('#escort').click(function(event){
    $('#front').show();
    $('#frontRear').show();
  });
  $('#front').click(function(event){
    $('#front').show();
    $('#frontRear').show();
    $('.titleHide').hide();
    $('.escortFrontTitle').show();
  });
  $('#frontRear').click(function(event){
    $('#front').show();
    $('#frontRear').show();
    $('.titleHide').hide();
    $('.escortFRTitle').show();
  });
  $('#k40').click(function(event){
    $('.optional').hide();
    $('#k40').show();
    $('#escort').show();
    $('.titleHide').hide();
    $('.k40Title').show();
  });
  $('#clearBra').click(function(event){
    $('.optional').hide();
    $('#frontHoodBikini').show();
    $('#wholeFrontEnd').show();
  });
  $('#frontHoodBikini').click(function(event){
    $('.optional').hide();
    $('#frontHoodBikini').show();
    $('#wholeFrontEnd').show();
    $('.titleHide').hide();
    $('.cbFrontHoodTitle').show();
  });
  $('#wholeFrontEnd').click(function(event){
    $('.optional').hide();
    $('#frontHoodBikini').show();
    $('#wholeFrontEnd').show();
    $('.titleHide').hide();
    $('.cbWholeFrontTitle').show();
  });
  $('#puddleLights').click(function(event){
    $('.optional').hide();
    $('.titleHide').hide();
    $('.puddleLightsTitle').show();
  });
  $('#dvr').click(function(event){
    $('.optional').hide();
    $('.titleHide').hide();
    $('.dvrTitle').show();
  });
  $('#customLeather').click(function(event){
    $('.optional').hide();
    $('#twoToneStitch').show();
  });
  $('#twoToneStitch').click(function(event){
    $('.optional').hide();
    $('#twoToneStitch').show();
    $('.titleHide').hide();
    $('.twoToneStitchTitle').show();
  });
  $('#fogLights').click(function(event){
    $('.optional').hide();
    $('.titleHide').hide();
    $('.fogLightsTitle').show();
  });
  $('#sts').click(function(event){
    $('.optional').hide();
    $('.titleHide').hide();
    $('.stsTitle').show();
  });

//ACCESSORIES MENU END
//---------------------------------------
  $('#cat1op1').click(function(event){
    $('.mediaContent').hide();
    $('.video1').show();
    document.getElementById('videoCont1').play();
  });

  $('#cat1op2').click(function(event){
    $('.mediaContent').hide();
    $('.image1').show();
    document.getElementById('videoCont1').pause();
  });

  $('.cat1').click(function(event){
    $('.catArea').hide();
    $('#cat1').show();
  });
  $('.cat2').click(function(event){
    $('.catArea').hide();
    $('#cat2').show();
  });
  $('.cat3').click(function(event){
    $('.catArea').hide();
    $('#cat3').show();
  });
});
